CREATE TABLE ALUMNOS
(
    PADRON          NUMERIC(10) NOT NULL PRIMARY KEY ,
    NOMBRE          VARCHAR(30),
    APELLIDO        VARCHAR(30),
    MAIL            VARCHAR(100),
    ABANDONO        BOOL NOT NULL,
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0
);


CREATE TABLE MATERIAS
(
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_MATERIA  VARCHAR(80),
    CUATRIMESTRE    TINYINT,
    ANIO            YEAR,
    ELIMINADO       BOOL DEFAULT 0,

    CONSTRAINT CK_CUATRIMESTRE_VALIDO CHECK (CUATRIMESTRE IN (1, 2)),
    CONSTRAINT COMBINACION_UNICA_MATERIAS unique (NOMBRE_MATERIA, CUATRIMESTRE, ANIO),
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE EVALUACIONES
(
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TIPO            ENUM("Parcial", "Oral", "Final", "TP", "Recuperatorio"),
    NOMBRE          VARCHAR(100),
    ID_MATERIA      INT,
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0,

    CONSTRAINT FK_ID_MATERIA FOREIGN KEY (ID_MATERIA)
        REFERENCES MATERIAS(ID),
    CONSTRAINT COMBINACION_UNICA_EVALUACIONES UNIQUE (TIPO, NOMBRE, ID_MATERIA)

);


CREATE TABLE NOTAS
(
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_EVALUACION   INT,
    PADRON_ALUMNO   NUMERIC(10),
    NOTA            NUMERIC(2),
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0,

    CONSTRAINT FK_PADRON_ALUMNO FOREIGN KEY (PADRON_ALUMNO)
        REFERENCES ALUMNOS(PADRON),
    CONSTRAINT FK_ID_EVALUACION FOREIGN KEY (ID_EVALUACION)
        REFERENCES EVALUACIONES(ID),
    CONSTRAINT COMBINACION_UNICA_NOTAS UNIQUE (ID_EVALUACION, PADRON_ALUMNO)
);

CREATE TABLE CLASES
(
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PROFESORES      JSON,
    FECHA           DATE,
    HORARIO         TIME,
    TEMA            VARCHAR(200),
    ELIMINADO       BOOL DEFAULT 0
);

CREATE TABLE ASISTENCIAS
(
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FECHA           DATETIME,
    PADRON_ALUMNO   NUMERIC(10,0),
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0,

    CONSTRAINT FK_PADRON FOREIGN KEY (PADRON_ALUMNO)
    	REFERENCES ALUMNOS(PADRON)
);


CREATE TABLE GRUPOS
(
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(50) NOT NULL,
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0
);


CREATE TABLE GRUPO_ALUMNO
(
    ID_GRUPO        INT ,
    PADRON_ALUMNO   NUMERIC(10),
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0,


    PRIMARY KEY(ID_GRUPO, PADRON_ALUMNO),
    CONSTRAINT FK_ID_GRUPO FOREIGN KEY (ID_GRUPO)
    	REFERENCES GRUPOS(ID),
    CONSTRAINT FK_PADRON_ALUMNOS FOREIGN KEY (PADRON_ALUMNO)
    	REFERENCES ALUMNOS(PADRON)
);


CREATE TABLE GRUPOS_TP (

    ID_EQUIPO       INT NOT NULL,
    ID_INSTANCIA    INT NOT NULL,
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0,

    PRIMARY KEY (ID_EQUIPO, ID_INSTANCIA),
    CONSTRAINT FK_EQUIPO FOREIGN KEY (ID_EQUIPO)
        REFERENCES GRUPOS(ID),
    CONSTRAINT FK_INSTANCIA FOREIGN KEY (ID_INSTANCIA)
        REFERENCES EVALUACIONES(ID)
);

CREATE TABLE USUARIOS (
    ID_USUARIO      INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE          VARCHAR(50) NOT NULL UNIQUE,
    PASS            VARCHAR(50) NOT NULL,
    FECHA_CREACION  DATETIME DEFAULT CURRENT_TIMESTAMP,
    ELIMINADO       BOOL DEFAULT 0
);

CREATE TABLE HISTORIAL (
    ID_REGISTRO     INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ACCION          VARCHAR(50) NOT NULL,
    DESCRIPCION     VARCHAR(100),
    ID_USUARIO      INT NOT NULL,
    ELIMINADO       BOOL DEFAULT 0,

    CONSTRAINT FK_USUARIO FOREIGN KEY (ID_USUARIO)
        REFERENCES USUARIOS(ID_USUARIO)
);

INSERT INTO USUARIOS (NOMBRE, PASS) VALUES ('BrunoLanzillota', 'linustorvaldsroot');

INSERT INTO ALUMNOS (PADRON, NOMBRE, APELLIDO, MAIL, ABANDONO) VALUES (115599, 'Agustin', 'Maseda', 'amaseda@fi.uba.ar', 0);
