CREATE TABLE ALUMNOS
(
    PADRON          NUMERIC(10) NOT NULL PRIMARY KEY ,
    NOMBRE          VARCHAR(30),
    APELLIDO        VARCHAR(30),
    MAIL            VARCHAR(100),
    ABANDONO   BOOL NOT NULL
);

CREATE TABLE EVALUACIONES_TIPOS
(
    ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TIPO        VARCHAR(50)
);

CREATE TABLE EVAL_INSTANCIAS
(
    ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_TIPO     INT,
    CONSTRAINT FK_ID_TIPO FOREIGN KEY (ID_TIPO)
        REFERENCES EVALUACIONES_TIPOS(ID)
        ON DELETE CASCADE,
    NOMBRE      VARCHAR(100),
    CUATRIMESTRE TINYINT,
    ANIO         YEAR
);

CREATE TABLE NOTAS
(
    ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_INSTANCIA INT,
    CONSTRAINT FK_ID_INSTANCIA FOREIGN KEY (ID_INSTANCIA)
        REFERENCES EVAL_INSTANCIAS(ID)
        ON DELETE CASCADE,
    PADRON NUMERIC(10),
    CONSTRAINT FK_PADRON_ALUMNO FOREIGN KEY (PADRON)
        REFERENCES ALUMNOS(PADRON),
    NOTA    NUMERIC(2)
);


CREATE TABLE ASISTENCIAS (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FECHA DATE,
    PADRON_ALUMNO NUMERIC(10,0),
    CONSTRAINT FK_PADRON FOREIGN KEY (PADRON_ALUMNO)
    	REFERENCES ALUMNOS(PADRON)
);


CREATE TABLE EQUIPOS (
    ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE      VARCHAR(50) NOT NULL
);



CREATE TABLE EQUIPO_ALUMNO(
    ID_EQUIPO INT ,
    PADRON_ALUMNO NUMERIC(10),
    PRIMARY KEY(ID_EQUIPO, PADRON_ALUMNO),
    CONSTRAINT FK_ID_GRUPO FOREIGN KEY (ID_EQUIPO)
    	REFERENCES EQUIPOS(ID),
    CONSTRAINT FK_PADRON_ALUMNOS FOREIGN KEY (PADRON_ALUMNO)
    	REFERENCES ALUMNOS(PADRON)
);


CREATE TABLE EQUIPO_TP (
    ID_EQUIPO    INT NOT NULL,
    ID_INSTANCIA INT NOT NULL,
    PRIMARY KEY (ID_EQUIPO, ID_INSTANCIA),
    CONSTRAINT FK_EQUIPO FOREIGN KEY (ID_EQUIPO)
        REFERENCES EQUIPOS(ID),
    CONSTRAINT FK_INSTANCIA FOREIGN KEY (ID_INSTANCIA)
        REFERENCES EVAL_INSTANCIAS(ID)
);

CREATE TABLE USUARIOS (
    ID_USUARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    PASS VARCHAR(255) NOT NULL
);